name: luckynumberapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - Image/105769079_10217500208479055_1053899048265455769_n.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: Font/Pacifico-Regular.ttf


